server:
  port: 8877
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

spring:
  application:
    name: harmony-server
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

logging:
  level:
    org.example: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
